### ISSUE TITLE
Trying to create a Setup for the following 

### ISSUE THREAD

**Issue by pairmike** [Proligence/OrchardTesting#1]
I have a service which contains the following in a method under test.  I'm having trouble creating the Setup for it in the unit test.

 var partRecord = _orchardServices.ContentManager.New<FINRAPaymentPart>("FINRAPayment");
partRecord.Recurring = recurring;
 _orchardServices.ContentManager.Create(partRecord, VersionOptions.Published);

In my unit test, I have the following:

   var finraPaymentPart = ContentFactory.CreateContentItem<FINRAPaymentPart>(123, "FINRAPayment", new FINRAPaymentPart { Record = new FINRAPaymentPartRecord() }, new InfosetPart());
            finraPaymentPart.As<FINRAPaymentPart>();

**\*           OrchardServices.ContentManagerMock.Setup<FINRAPaymentPart>(o => o.New<FINRAPaymentPart>("FINRAPayment")).Returns(finraPaymentPart);     

```
    OrchardServices.ContentManager.Create(finraPaymentPart, VersionOptions.Published);
```

The compiler fails with an error on the **\* line with the following message.  
Invalid setup on a non-member method: o => o.New<FINRAPaymentPart>("FINRAPayment")

**Comment by MpDzik** [comment]
Please try to use the `ExpectNewItem` helper method on `ContentManagerMock`, for example:

```
OrchardServices.ContentManagerMock.ExpectNewItem("FINRAPayment", finraPaymentPart.ContentItem);
```

**Comment by pairmike** [comment]
Thanks.  I would have not figured that out.
